### PR TITLE
Kh/polishing

### PR DESCRIPTION
**Pull request by kevinhalliday**
This PR lumps together a few efforts. But all fall under the - let's get this ready to announce / submit for review in browser stores. I think the most valuable review I could ask of you too is that you pull it, try it, and report back. Try the standard flows, and try to push it into failure cases. 

The changes are:

- styling updates. big one is the font change. I changed the style to use monospace font cause I thought it gave it a cool dev-esque vibe. I will change it back if you two dont approve
- make sure the neptune provider address beats out the metamask address
- improving docs / inline comments
- bringing all the logic necessary for the controller to "sync" itself with the server into one spot. adding the piping for other parts of the extension to tell the controller to sync up. and having them do that more often
- refactoring ui components. reducing inline styles. and some other cleanup

addresses:

https://github.com/recursive-research/neptune/issues/10

### CODE REVIEW

**Comment by kevinhalliday** [comment]
seems like auto-impersonation is not working right after creating a new fork. im looking into it

**Review by ttarsi — APPROVED** [review]
The good
- I like the new font
- i'm glad we have the initial error message "neptune isn't running". I think that will clear up a lot of confusion that could happen on start
- page reloading works well and we inject ahead of metamask
- builds fine for me

The bad:
- When i close and reopen the wallet, it takes a long time for the forks to reload - it's on the order of 15 seconds
- it also happens when I open a new app (e.g. I'm connected on the Rift app, then go to the Uniswap app and open Neptune. Actually, I've been trying to open the extension for about 2 minutes on uniswap right now, and I'm just getting the loading circle
- These seem to be related and I'm not sure how much it's due to my bad wifi. But it was a problem previously as well, when I had good wifi 

Going to approve and trust your guys judgement on the loading state

**Comment by kevinhalliday** [comment]
> The bad:
> 
>     * When i close and reopen the wallet, it takes a long time for the forks to reload - it's on the order of 15 seconds
> 
>     * it also happens when I open a new app (e.g. I'm connected on the Rift app, then go to the Uniswap app and open Neptune. Actually, I've been trying to open the extension for about 2 minutes on uniswap right now, and I'm just getting the loading circle
> 
>     * These seem to be related and I'm not sure how much it's due to my bad wifi. But it was a problem previously as well, when I had good wifi
> 

this is quite curious. obviously not ideal. I'll try to recreate. neither Mike nor I seemed to run into this. it _should_ only ever take a bit to open the extension when it is creating a fork - this process could hang for a while if wifi is bad. but if a fork already exists (which would be the case, if you're just opening and closing), i'm not sure why it would take so long.

**Review by ttarsi — APPROVED** [review]
lgtm

**Pull request merged**
